name: ReferralCodesHub build

on:
  push:

env:
  DOTNET_VERSION: 8.0.204
  DOTNET_INSTALL_KEY: 'ubuntu-latest-dotnet'

jobs:
  build-and-test:

    name: build-ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
