name: ReferralCodesHub build

on:
  push:

env:
  DOTNET_VERSION: 8.0.204
  DOTNET_INSTALL_KEY: 'ubuntu-latest-dotnet'

jobs:
  build-and-test:

    name: build-ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
   
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache nuget packages
      id: cache-nuget
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/packages.lock.json') }}
   
    - name: Restore nuget packages
      if: ${{ steps.cache-nuget.outputs.cache-hit != 'true' }}
      run: dotnet restore --locked-mode
      
    - name: Build
      run: dotnet build --configuration Release --no-restore